service:
  type: ClusterIP

ingress:
  enabled: true
  tls: true
  extraHosts:
    - name: "*.domain.tld"
      path: /

yourls:
  password: "test-yourls"

mysql:
  auth:
    rootPassword: "test-root"
    password: "test-user"
