ingress:
  enabled: true
  tls: true

service:
  type: ClusterIP

metrics:
  enabled: true

yourls:
  password: "test-yourls"

mariadb:
  auth:
    rootPassword: "test-root"
    password: "test-user"
