owner: YOURLS
repo: charts
package-path: public
remote: origin
chart-dirs:
  - charts
excluded-charts:
  - common
helm-extra-args: --timeout 800
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
