owner: YOURLS
repo: charts
remote: origin
target-branch: main
sign: true
key: YOURLS Org
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
generate-release-notes: true
debug: true
