apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "yourls.fullname" . }}
  labels:
    app: "{{ template "yourls.fullname" . }}"
    chart: "{{ template "yourls.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: "{{ template "yourls.fullname" . }}"
      release: {{ .Release.Name | quote }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "yourls.fullname" . }}"
        chart: "{{ template "yourls.chart" . }}"
        release: {{ .Release.Name | quote }}
      {{- if or .Values.podAnnotations .Values.metrics.enabled }}
      annotations:
      {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.podAnnotations }}
        {{- toYaml .Values.metrics.podAnnotations | nindent 8 }}
      {{- end }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "status.localhost"
      {{- if .Values.initContainers }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: "{{ template "yourls.fullname" . }}"
          image: {{ template "yourls.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: YOURLS_DB_HOST
              value: {{ include "yourls.databaseHost" . | quote }}
            - name: YOURLS_DB_NAME
              value: {{ include "yourls.databaseName" . | quote }}
            - name: YOURLS_DB_USER
              value: {{ include "yourls.databaseUser" . | quote }}
            - name: YOURLS_DB_PASS
              valueFrom:
                secretKeyRef:
                {{- if .Values.mysql.enabled }}
                  name: {{ template "yourls.mysql.fullname" . }}
                  key: mysql-password
                {{- else }}
                  name: {{ template "yourls.dbSecret" . }}
                  key: db-password
                {{- end }}
            - name: YOURLS_DB_PREFIX
              value: {{ .Values.yourls.tablePrefix | quote }}
            - name: YOURLS_SITE
              value: {{ .Values.yourls.site | quote }}
            - name: YOURLS_USER
              value: {{ .Values.yourls.username | quote }}
            - name: YOURLS_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "yourls.applicationSecret" . }}
                  key: yourls-password
          {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          livenessProbe:
            httpGet:
              path: /admin/install.php
            {{- if not .Values.healthcheckHttps }}
              port: http
            {{- else }}
              port: https
              scheme: HTTPS
            {{- end }}
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
          {{- if not .Values.disableAdminPanelReadinessProbe }}
            httpGet:
              path: /admin/install.php
            {{- if not .Values.healthcheckHttps }}
              port: http
            {{- else }}
              port: https
              scheme: HTTPS
            {{- end }}
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /var/www/html
              name: yourls-data
          {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.metrics.enabled }}
        - name: metrics
          image: {{ template "metrics.image" . }}
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
          command: [ '/bin/apache_exporter', '-scrape_uri', 'http://status.localhost:80/server-status/?auto']
          ports:
            - name: metrics
              containerPort: 9117
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.metrics.resources | nindent 12 }}
{{- end }}
      volumes:
        - name: yourls-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "yourls.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{ end }}
      {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end -}}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
