# https://docs.github.com/actions

name: Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '43 2 * * 6'

jobs:
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Checkov scanner
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: charts/yourls
          framework: helm
          download_external_modules: false
          quiet: true

      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: results.sarif
