# https://docs.github.com/actions

name: Analysis

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '43 2 * * 6'

jobs:
  kubesec:
    name: Kubesec
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1.1

      - name: Add Helm repos
        run: helm dependency update charts/yourls

      - name: Render chart
        run: helm template kubesec charts/yourls > yourls-template.yml

      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@v0.0.2
        with:
          input: yourls-template.yml
          format: template
          template: '@/templates/sarif.tpl'
          output: kubesec-results.sarif
          exit-code: "0"

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: kubesec-results.sarif
