name: Charts CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint
          config: config.yaml
#      - name: Create kind cluster
#        uses: helm/kind-action@v1.0.0-alpha.3
#        # Only build a kind cluster if there are chart changes to test.
#        if: steps.lint.outputs.changed == 'true'
#      - name: Run chart-testing (install)
#        uses: helm/chart-testing-action@v1.0.0-rc.2
#        with:
#          command: install
#          config: config.yaml

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0-rc.2
        with:
          charts_repo_url: ${{ secrets.CHARTS_URL }}
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
