name: Charts CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.1
        with:
          command: lint
          config: config.yaml
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-alpha.3
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.1
        with:
          command: install
          config: config.yaml

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    container: quay.io/helmpack/chart-releaser:latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        run: cr upload --config config.yaml
      - name: Index
        run: cr index --config config.yaml
