# https://docs.github.com/actions

name: Using chart-testing

on:
  workflow_call:
    inputs:
      action:
        required: false
        default: install
        type: string

jobs:
  ct:
    name: ${{ inputs.command }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Set up Helm
        uses: azure/setup-helm@v2.0

      - uses: actions/setup-python@v2.3.2

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: startsWith(inputs.action, 'install')

      - name: Run chart-testing (${{ inputs.command }})
        run: ct ${{ inputs.command }} --config config.yaml
